#### what is numpy?
##### Numpy is a scientific computing library for python that provides support for multidimentional array and mathematical problems

In [1]:
#import numpy library
import numpy as np

In [3]:
print("1-D Array")
arr1 = [1,2,3,4,5]
print(arr1)
print("----------------------------")

print("2-D Array")
arr2 = [[1,2,3,4,5],[6,7,8,9,10]]
print(arr2)
print("----------------------------")

print("1-D Array")
arr3 = [[1,2,3,4,5],[6,7,8,9,10],[11,12,13,14,15]]
print(arr3)
print("----------------------------")

1-D Array
[1, 2, 3, 4, 5]
----------------------------
2-D Array
[[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]]
----------------------------
1-D Array
[[1, 2, 3, 4, 5], [6, 7, 8, 9, 10], [11, 12, 13, 14, 15]]
----------------------------


#### why Numpy?
##### We can store multidimmentional Array in numpy which is an advatange

In [15]:
print("1-D Array")
arr1 = np.array([1,2,3,4,5])
print(arr1)
print("----------------------------")

print("2-D Array")
arr2 = np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(arr2)
print("----------------------------")


print("3-D Array")
arr3 = np.array([[[1, 2, 3], [4, 5, 18]],
                 [[6, 7, 8], [9, 10, 19]],
                 [[11, 12, 20], [13, 14, 15]]])
print(arr3)
print("----------------------------")


1-D Array
[1 2 3 4 5]
----------------------------
2-D Array
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
----------------------------
3-D Array
[[[ 1  2  3]
  [ 4  5 18]]

 [[ 6  7  8]
  [ 9 10 19]]

 [[11 12 20]
  [13 14 15]]]
----------------------------


In [17]:
#type,size,shape of the array
print("Type of the array")
print(type(arr1))
print("----------------------------")

print("size of the arrays:-")
print(arr1.size)
print(arr2.size)
print(arr3.size)
print("----------------------------")

print("shape of the arrays:-")
print(arr1.shape)
print(arr2.shape)
print(arr3.shape)
print("----------------------------")

print("dtype of the arrays:-")
print(arr1.dtype)
print(arr2.dtype)
print(arr3.dtype)
print("----------------------------")




Type of the array
<class 'numpy.ndarray'>
----------------------------
size of the arrays:-
5
10
18
----------------------------
shape of the arrays:-
(5,)
(2, 5)
(3, 2, 3)
----------------------------
dtype of the arrays:-
int32
int32
int32
----------------------------


In [22]:
arr4 = np.array([[1,2.5],[3.9,4]])
print(arr4)
print(arr4.shape)
print(arr4.size)
print(arr4.dtype)

[[1.  2.5]
 [3.9 4. ]]
(2, 2)
4
float64


In [24]:
#transpose of an array or matrix
arr5 = arr2.transpose()
print(arr5)

[[ 1  6]
 [ 2  7]
 [ 3  8]
 [ 4  9]
 [ 5 10]]
