#### what is numpy?
##### Numpy is a scientific computing library for python that provides support for multidimentional array and mathematical problems

In [63]:
#import numpy library
import numpy as np

In [64]:
print("1-D Array")
arr1 = [1,2,3,4,5]
print(arr1)
print("----------------------------")

print("2-D Array")
arr2 = [[1,2,3,4,5],[6,7,8,9,10]]
print(arr2)
print("----------------------------")

print("1-D Array")
arr3 = [[1,2,3,4,5],[6,7,8,9,10],[11,12,13,14,15]]
print(arr3)
print("----------------------------")

1-D Array
[1, 2, 3, 4, 5]
----------------------------
2-D Array
[[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]]
----------------------------
1-D Array
[[1, 2, 3, 4, 5], [6, 7, 8, 9, 10], [11, 12, 13, 14, 15]]
----------------------------


#### why Numpy?
##### We can store multidimmentional Array in numpy which is an advatange

In [65]:
print("1-D Array")
arr1 = np.array([1,2,3,4,5])
print(arr1)
print("----------------------------")

print("2-D Array")
arr2 = np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(arr2)
print("----------------------------")


print("3-D Array")
arr3 = np.array([[[1, 2, 3], [4, 5, 18]],
                 [[6, 7, 8], [9, 10, 19]],
                 [[11, 12, 20], [13, 14, 15]]])
print(arr3)
print("----------------------------")


1-D Array
[1 2 3 4 5]
----------------------------
2-D Array
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
----------------------------
3-D Array
[[[ 1  2  3]
  [ 4  5 18]]

 [[ 6  7  8]
  [ 9 10 19]]

 [[11 12 20]
  [13 14 15]]]
----------------------------


In [66]:
#type,size,shape of the array
print("Type of the array")
print(type(arr1))
print("----------------------------")

print("size of the arrays:-")
print(arr1.size)
print(arr2.size)
print(arr3.size)
print("----------------------------")

print("shape of the arrays:-")
print(arr1.shape)
print(arr2.shape)
print(arr3.shape)
print("----------------------------")

print("dtype of the arrays:-")
print(arr1.dtype)
print(arr2.dtype)
print(arr3.dtype)
print("----------------------------")




Type of the array
<class 'numpy.ndarray'>
----------------------------
size of the arrays:-
5
10
18
----------------------------
shape of the arrays:-
(5,)
(2, 5)
(3, 2, 3)
----------------------------
dtype of the arrays:-
int32
int32
int32
----------------------------


In [67]:
arr4 = np.array([[1,2.5],[3.9,4]])
print(arr4)
print(arr4.shape)
print(arr4.size)
print(arr4.dtype)

[[1.  2.5]
 [3.9 4. ]]
(2, 2)
4
float64


In [68]:
#transpose of an array or matrix
arr5 = arr2.transpose()
print(arr5)

[[ 1  6]
 [ 2  7]
 [ 3  8]
 [ 4  9]
 [ 5 10]]


In [69]:
# when we want an empty array with random data
np.empty((4,4),dtype=int)

array([[4128860, 6029375, 3801155, 5570652],
       [6619251, 7536754, 6815836, 6029424],
       [7340097, 4456560, 7602273, 6029409],
       [7274572, 6357091,     108,     659]])

In [70]:
# if we want only 1 be the element of the array
arr6 = np.ones((2,4),dtype=int)
print(arr6)

[[1 1 1 1]
 [1 1 1 1]]


In [71]:
#if we want 0 be the element of the array
arr7=np.zeros((3,3),dtype=int)
print(arr7)

[[0 0 0]
 [0 0 0]
 [0 0 0]]


In [72]:
arr6 = np.ones((2,4),dtype=bool)
print(arr6)

[[ True  True  True  True]
 [ True  True  True  True]]


In [73]:
arr6 = np.zeros((2,4),dtype=str)
print(arr6)

[['' '' '' '']
 ['' '' '' '']]


In [74]:
arr6 = np.zeros((2,4),dtype=bool)
print(arr6)

[[False False False False]
 [False False False False]]


In [75]:
# to print something like for loop
arr8 = np.arange(2,20,2)
print(arr8)

[ 2  4  6  8 10 12 14 16 18]


In [76]:
arr8= arr8.reshape(3,3)
arr8

array([[ 2,  4,  6],
       [ 8, 10, 12],
       [14, 16, 18]])

In [77]:
arr9 = np.arange(1,100,2)
print(arr9)

[ 1  3  5  7  9 11 13 15 17 19 21 23 25 27 29 31 33 35 37 39 41 43 45 47
 49 51 53 55 57 59 61 63 65 67 69 71 73 75 77 79 81 83 85 87 89 91 93 95
 97 99]


In [78]:
arr9 = arr9.reshape(10,5)
print(arr9)

[[ 1  3  5  7  9]
 [11 13 15 17 19]
 [21 23 25 27 29]
 [31 33 35 37 39]
 [41 43 45 47 49]
 [51 53 55 57 59]
 [61 63 65 67 69]
 [71 73 75 77 79]
 [81 83 85 87 89]
 [91 93 95 97 99]]


In [79]:
arr8 = arr8.flatten()
arr8

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18])

In [80]:
arr8 = arr8.ravel()
arr8

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18])

#### what is the difference  between ravel and flatten?
##### Ravel:- 1) returns only reference or view of original array
##### 2) it does not create a new array
##### 3) it does not change the shape of the array
##### Flatten:- 1) returns a copy of original array
##### 2) it creates a new array
##### 3) it changes the shape of the array


#### array slicing

In [81]:
arr9 = np.arange(1,51)
arr9 = arr9.reshape(10,5)
print(arr9)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]
 [26 27 28 29 30]
 [31 32 33 34 35]
 [36 37 38 39 40]
 [41 42 43 44 45]
 [46 47 48 49 50]]


In [82]:
arr9[0]

array([1, 2, 3, 4, 5])

In [83]:
arr9[0][1]

2

In [84]:
arr9[3,4]

20

In [85]:
# if we want to print from 2nd row to 4th row
arr9[2:5]  #[index of starting row:index of endingrow+1]

array([[11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [86]:
arr9[:,4]

array([ 5, 10, 15, 20, 25, 30, 35, 40, 45, 50])

In [87]:
arr9[2:5,3]

array([14, 19, 24])

In [88]:
arr9[:,2:5]


array([[ 3,  4,  5],
       [ 8,  9, 10],
       [13, 14, 15],
       [18, 19, 20],
       [23, 24, 25],
       [28, 29, 30],
       [33, 34, 35],
       [38, 39, 40],
       [43, 44, 45],
       [48, 49, 50]])

In [89]:
arr9[1,2:5]

array([ 8,  9, 10])

In [118]:
# creating teo arrays
a = np.arange(0,18).reshape(6,3)
b = np.arange(5,91,5).reshape(6,3)
print(a)
print("----------------------------")
print(b)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]
 [12 13 14]
 [15 16 17]]
----------------------------
[[ 5 10 15]
 [20 25 30]
 [35 40 45]
 [50 55 60]
 [65 70 75]
 [80 85 90]]


In [91]:
a*b #or np.multiply(a,b)

array([[   0,   10,   30],
       [  60,  100,  150],
       [ 210,  280,  360],
       [ 450,  550,  660],
       [ 780,  910, 1050],
       [1200, 1360, 1530]])

In [92]:
a+b

array([[  5,  11,  17],
       [ 23,  29,  35],
       [ 41,  47,  53],
       [ 59,  65,  71],
       [ 77,  83,  89],
       [ 95, 101, 107]])

In [93]:
np.add(a,b)

array([[  5,  11,  17],
       [ 23,  29,  35],
       [ 41,  47,  53],
       [ 59,  65,  71],
       [ 77,  83,  89],
       [ 95, 101, 107]])

In [94]:
np.multiply(a,b)

array([[   0,   10,   30],
       [  60,  100,  150],
       [ 210,  280,  360],
       [ 450,  550,  660],
       [ 780,  910, 1050],
       [1200, 1360, 1530]])

In [95]:
a-b

array([[ -5,  -9, -13],
       [-17, -21, -25],
       [-29, -33, -37],
       [-41, -45, -49],
       [-53, -57, -61],
       [-65, -69, -73]])

In [97]:
np.subtract(a,b)

array([[ -5,  -9, -13],
       [-17, -21, -25],
       [-29, -33, -37],
       [-41, -45, -49],
       [-53, -57, -61],
       [-65, -69, -73]])

In [98]:
a/b

array([[0.        , 0.1       , 0.13333333],
       [0.15      , 0.16      , 0.16666667],
       [0.17142857, 0.175     , 0.17777778],
       [0.18      , 0.18181818, 0.18333333],
       [0.18461538, 0.18571429, 0.18666667],
       [0.1875    , 0.18823529, 0.18888889]])

#### why the error is coming in the first go if we do not reshape b?
##### because we know for matrix multiplication column of A = row of B , so we need to reshape it

In [100]:
b=b.reshape(3,6)
b

array([[ 5, 10, 15, 20, 25, 30],
       [35, 40, 45, 50, 55, 60],
       [65, 70, 75, 80, 85, 90]])

In [101]:
#matrixmultiplication
a@b

array([[ 165,  180,  195,  210,  225,  240],
       [ 480,  540,  600,  660,  720,  780],
       [ 795,  900, 1005, 1110, 1215, 1320],
       [1110, 1260, 1410, 1560, 1710, 1860],
       [1425, 1620, 1815, 2010, 2205, 2400],
       [1740, 1980, 2220, 2460, 2700, 2940]])

In [102]:
a.dot(b)

array([[ 165,  180,  195,  210,  225,  240],
       [ 480,  540,  600,  660,  720,  780],
       [ 795,  900, 1005, 1110, 1215, 1320],
       [1110, 1260, 1410, 1560, 1710, 1860],
       [1425, 1620, 1815, 2010, 2205, 2400],
       [1740, 1980, 2220, 2460, 2700, 2940]])

### maximum and minimum of an array

In [104]:
print(a.max())
print(b.max())

17
90


In [105]:
print(a.min())
print(b.min())

0
5


#### to get the array position of high and low

In [106]:
print(a.argmax())
print(b.argmax())

17
17


In [107]:
print(a.argmin())
print(b.argmin())

0
0


#### sum of all the elements of a matrix

In [109]:
print(a.sum())
print(b.sum())

153
855


#### sum of each row when axis=1
#### sum of each column when axis = 0

In [113]:
print(np.sum(a,axis=1))
print(np.sum(b,axis=0))

[ 3 12 21 30 39 48]
[105 120 135 150 165 180]


#### mean,square value,standard deviation,log value

In [119]:
print("mean is :",np.mean(b))
print("----------------------------")

print("square root is:",np.sqrt(b))
print("----------------------------")

print("standard deviation is :",np.std(b))
print("----------------------------")

print("log value is:",np.log(b))
print("----------------------------")


mean is : 47.5
----------------------------
square root is: [[2.23606798 3.16227766 3.87298335]
 [4.47213595 5.         5.47722558]
 [5.91607978 6.32455532 6.70820393]
 [7.07106781 7.41619849 7.74596669]
 [8.06225775 8.36660027 8.66025404]
 [8.94427191 9.21954446 9.48683298]]
----------------------------
standard deviation is : 25.940637360455632
----------------------------
log value is: [[1.60943791 2.30258509 2.7080502 ]
 [2.99573227 3.21887582 3.40119738]
 [3.55534806 3.68887945 3.80666249]
 [3.91202301 4.00733319 4.09434456]
 [4.17438727 4.24849524 4.31748811]
 [4.38202663 4.44265126 4.49980967]]
----------------------------


#### visualization of trigonametric functions

In [121]:
import matplotlib.pyplot as plt
plt.style.use('dark_background')

In [122]:
np.pi

3.141592653589793

In [127]:
# for 90 degree
print(np.sin(np.pi/2))
print(np.cos(np.pi/2))
print(np.tan(np.pi/2))


1.0
6.123233995736766e-17
1.633123935319537e+16


In [128]:
# for 30 degree
print(np.sin(np.pi/6))
print(np.cos(np.pi/6))
print(np.tan(np.pi/6))


0.49999999999999994
0.8660254037844387
0.5773502691896257


In [129]:
np.tan(0)

0.0

#### Matplot with numpy
(first visit the matplot codes then this)